"""PDF text extraction with an OCR fallback — shared across channels.

The bot runs on Max auth (Agent SDK), whose message path is text-only:
images and document content blocks are dropped before they reach the
model. So to let the model *read* a PDF at all, we have to turn it into
text on our side and inject that text the same way the Telegram text-file
path already does for `.txt`/`.md`.

Two-tier strategy:
1. **Text layer** (the common case): digital PDFs — exported lab reports,
   statements, anything generated by software — carry a selectable text
   layer. PyMuPDF pulls it out locally, fast and free.
2. **OCR fallback** (scanned / photographed paper): when the text layer is
   empty or near-empty, the PDF is almost certainly page images. We render
   each page to a PNG and hand it to OpenAI's vision model to transcribe.
   This reuses the OPENAI_API_KEY already present for Whisper/TTS.

Both tiers are channel-agnostic — Telegram and Signal both call
`extract_pdf_text`.
"""

from __future__ import annotations

import asyncio
import base64
import logging

import aiohttp

from src.channels._http import make_session

log = logging.getLogger(__name__)

# Below this many non-whitespace characters across the whole document we
# assume there's no usable text layer (scanned/photographed) and fall back
# to OCR. A genuine lab report or statement has hundreds to thousands.
_TEXT_LAYER_MIN_CHARS = 80

# Default ceiling on how much extracted text we forward to the model — the
# Telegram text-file path uses the same 20k budget. Lab panels are tiny;
# this only bites on book-length PDFs.
_DEFAULT_MAX_CHARS = 20_000

# OCR is the expensive path (one vision call, render cost per page). Cap how
# many pages we'll OCR so a 200-page scan can't blow up latency/cost. The
# caller is told when we truncated so it can surface that to the user.
_DEFAULT_MAX_OCR_PAGES = 8

# Render DPI for OCR. 150 is a good legibility/size tradeoff for text-heavy
# documents; higher mostly inflates the payload without helping the model.
_OCR_DPI = 150

_OCR_MODEL = "gpt-4o"
_OCR_PROMPT = (
    "Transcribe ALL text from the following scanned document page(s) "
    "verbatim. Preserve tables as aligned plain text or markdown so rows "
    "and columns stay readable. Include every label, number, unit, and "
    "reference range exactly as shown. Do not summarize, interpret, or add "
    "commentary — output only the transcribed text."
)


class PdfExtract:
    """Result of a PDF extraction attempt.

    `method` is one of:
      - "text" — pulled from the PDF's text layer
      - "ocr"  — transcribed from rendered page images
      - "none" — nothing usable (no text layer and OCR unavailable/failed)
    """

    __slots__ = ("text", "method", "page_count", "ocr_pages", "char_truncated", "page_truncated")

    def __init__(
        self,
        text: str,
        method: str,
        page_count: int,
        ocr_pages: int = 0,
        char_truncated: bool = False,
        page_truncated: bool = False,
    ) -> None:
        self.text = text
        self.method = method
        self.page_count = page_count
        self.ocr_pages = ocr_pages          # pages actually OCR'd
        self.char_truncated = char_truncated  # text clipped to max_chars
        self.page_truncated = page_truncated  # pages beyond the OCR cap skipped

    @property
    def ok(self) -> bool:
        return self.method != "none" and bool(self.text.strip())


async def extract_pdf_text(
    data: bytes,
    *,
    openai_api_key: str = "",
    max_chars: int = _DEFAULT_MAX_CHARS,
    max_ocr_pages: int = _DEFAULT_MAX_OCR_PAGES,
) -> PdfExtract:
    """Extract text from PDF bytes, OCR'ing scanned pages when needed.

    Never raises for a malformed/encrypted PDF — returns a `PdfExtract`
    with `method="none"` so the caller can degrade gracefully to the
    plain "binary file received" acknowledgement.
    """
    # PyMuPDF is sync and CPU-bound; keep it off the event loop.
    try:
        text, page_count = await asyncio.to_thread(_extract_text_layer, data)
    except Exception as e:
        log.warning("PDF text-layer extraction failed: %s", e)
        return PdfExtract("", "none", 0)

    if len(text.strip()) >= _TEXT_LAYER_MIN_CHARS:
        clipped, truncated = _clip(text, max_chars)
        return PdfExtract(clipped, "text", page_count, char_truncated=truncated)

    # Sparse/empty text layer → scanned document. Try OCR.
    if not openai_api_key:
        log.info("PDF has no text layer and no OPENAI_API_KEY for OCR fallback")
        return PdfExtract("", "none", page_count)

    try:
        ocr_text, ocr_pages, page_truncated = await _ocr_pdf(
            data, openai_api_key, max_ocr_pages
        )
    except Exception as e:
        log.warning("PDF OCR fallback failed: %s", e)
        return PdfExtract("", "none", page_count)

    if not ocr_text.strip():
        return PdfExtract("", "none", page_count)

    clipped, truncated = _clip(ocr_text, max_chars)
    return PdfExtract(
        clipped, "ocr", page_count,
        ocr_pages=ocr_pages,
        char_truncated=truncated,
        page_truncated=page_truncated,
    )


def _clip(text: str, max_chars: int) -> tuple[str, bool]:
    if len(text) <= max_chars:
        return text, False
    return text[:max_chars] + f"\n\n[... truncated, {len(text)} chars total]", True


def _extract_text_layer(data: bytes) -> tuple[str, int]:
    """Pull the embedded text layer page by page. Sync; runs in a thread."""
    import pymupdf  # imported lazily so the dep is only needed when a PDF arrives

    parts: list[str] = []
    with pymupdf.open(stream=data, filetype="pdf") as doc:
        page_count = doc.page_count
        for page in doc:
            t = page.get_text("text")
            if t.strip():
                parts.append(t)
    return "\n".join(parts), page_count


def _render_pages_png(data: bytes, max_pages: int) -> tuple[list[bytes], int, bool]:
    """Render up to `max_pages` pages to PNG bytes. Sync; runs in a thread.

    Returns (png_list, total_page_count, truncated).
    """
    import pymupdf

    pngs: list[bytes] = []
    zoom = _OCR_DPI / 72.0  # PDF user space is 72 dpi
    matrix = pymupdf.Matrix(zoom, zoom)
    with pymupdf.open(stream=data, filetype="pdf") as doc:
        total = doc.page_count
        for i, page in enumerate(doc):
            if i >= max_pages:
                break
            pix = page.get_pixmap(matrix=matrix)
            pngs.append(pix.tobytes("png"))
    return pngs, total, total > max_pages


async def _ocr_pdf(
    data: bytes, api_key: str, max_pages: int
) -> tuple[str, int, bool]:
    """Render pages and transcribe them via OpenAI vision.

    All rendered pages go in a single chat-completion request as separate
    image blocks — cheaper on round-trips and lets the model keep
    page-to-page context (a table continuing across a page break).
    """
    pngs, _total, page_truncated = await asyncio.to_thread(
        _render_pages_png, data, max_pages
    )
    if not pngs:
        return "", 0, page_truncated

    content: list[dict] = [{"type": "text", "text": _OCR_PROMPT}]
    for png in pngs:
        b64 = base64.b64encode(png).decode("ascii")
        content.append({
            "type": "image_url",
            "image_url": {"url": f"data:image/png;base64,{b64}"},
        })

    payload = {
        "model": _OCR_MODEL,
        "messages": [{"role": "user", "content": content}],
        # Generous ceiling — a dense page of lab values is a lot of tokens.
        "max_tokens": 4096,
        "temperature": 0,
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    async with make_session() as session:
        async with session.post(
            "https://api.openai.com/v1/chat/completions",
            json=payload,
            headers=headers,
            timeout=aiohttp.ClientTimeout(total=120),
        ) as r:
            if r.status >= 400:
                body = await r.text()
                raise RuntimeError(f"OpenAI vision {r.status}: {body[:200]}")
            result = await r.json()

    text = (result["choices"][0]["message"]["content"] or "").strip()
    return text, len(pngs), page_truncated
